apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  labels:
    purpose: service
spec:
  selector:
    app: tomcat-deploy
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30865
  type: NodePort
